site_name: Maslow Unofficial Docs
site_description: 'Organizing the knowledge of the Maslow community'
site_author: 'Chris Mullins'
docs_dir: docs/
repo_name: 'cmullins70/maslowdocs'
repo_url: 'https://github.com/cmullins70/maslowdocs'
nav:
    - Home: index.md
theme:
  name: 'material'
